Added System Dashboard
sentrysoftware/grafana-dashboards pull request #16
Opened 2024-07-16 07:48 UTC by MohammedSentry

2024-07-30 15:43 UTC, NassimBtk commented on src/dashboards/System/System (MetricsHub).json
> +          "expr": "sum (system_memory_utilization_ratio{host_id=\"$host_id\", system_memory_usage=\"used\", site=\"$site\"})",
`"expr": "sum (system_memory_utilization_ratio{host_id=\"$host_id\", system_memory_state=\"used\", site=\"$site\"})",`

2024-07-30 15:43 UTC, NassimBtk commented on src/dashboards/System/System (MetricsHub).json
> +              "{__name__=\"system_memory_utilization_ratio\", agent_host_name=\"mk-win.internal.sentrysoftware.net\", connector_id=\"Linux\", host_id=\"mk-deb2\", host_name=\"mk-deb2.internal.sentrys
`"{__name__=\"system_memory_utilization_ratio\", agent_host_name=\"mk-win.internal.sentrysoftware.net\", connector_id=\"Linux\", host_id=\"mk-deb2\", host_name=\"mk-deb2.internal.sentrysoftware.net\", host_type=\"compute\", id=\"memory_usage\", os_type=\"linux\", site=\"Paris\", system_memory_limit=\"2063106048\", system_memory_state=\"used\"}": "Used memory"`

2024-07-30 15:43 UTC, NassimBtk commented on src/dashboards/System/System (MetricsHub).json
> +              "{__name__=\"system_memory_utilization_ratio\", agent_host_name=\"mk-win.internal.sentrysoftware.net\", connector_id=\"Linux\", host_id=\"mk-deb2\", host_name=\"mk-deb2.internal.sentrys
We need to rename the attribute key from `system_memory_usage` to `system_memory_state`

2024-07-30 15:43 UTC, NassimBtk commented on src/dashboards/System/System (MetricsHub).json
> +          "expr": "system_memory_usage_bytes{host_id=~\"$host_id\", site=\"$site\", system_memory_usage=~\"cached|buffers\"}",
`"expr": "system_memory_usage_bytes{host_id=~\"$host_id\", site=\"$site\", system_memory_state=~\"cached|buffers\"}",`

2024-07-30 15:43 UTC, NassimBtk commented on src/dashboards/System/System (MetricsHub).json
> +          "expr": "system_memory_usage_bytes{host_id=~\"$host_id\", site=\"$site\", system_memory_usage=~\"cached|buffers\"}",
We need to rename the attribute key from `system_memory_usage` to `system_memory_state`

2024-07-30 15:43 UTC, NassimBtk commented on src/dashboards/System/System (MetricsHub).json
> +          "legendFormat": "{{system_memory_usage}}",
Should be `"legendFormat": "{{system_memory_state}}",`

2024-07-30 15:43 UTC, NassimBtk commented on src/dashboards/System/System (MetricsHub).json
> +          "legendFormat": "{{system_memory_usage}}",
Should be `"legendFormat": "{{system_memory_state}}",`

2024-07-30 15:43 UTC, NassimBtk commented on src/dashboards/System/System (MetricsHub).json
> +          "expr": "sum (system_memory_utilization_ratio{host_id=\"$host_id\", system_memory_usage=\"used\", site=\"$site\"})",
We need to rename the attribute key from `system_memory_usage` to `system_memory_state`.

2024-08-02 15:42 UTC, bertysentry requested changes
Please update the dashboard, following the fix of our system connectors 😬🤷‍♂️

2024-08-07 13:55 UTC, bertysentry approved these changes

2024-08-07 17:33 UTC, merged